GET http://localhost:6000/api/fleets HTTP/1.1
Content-Type: application/json

{
     "name":"Thresher AH520",
        "description":"This implement is used to thresh",
        "purpose":"To thresh",
        "image":"fleet.jpg",
        "availability":"Currently available"
       
}